"""update projects table

Revision ID: 6e62af7c6a72
Revises: 7b8843bfb0e4
Create Date: 2025-07-20 14:32:22.677835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e62af7c6a72'
down_revision: Union[str, Sequence[str], None] = '7b8843bfb0e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('category', sa.String(), nullable=True))
    op.add_column('skills', sa.Column('proficiency', sa.Integer(), nullable=True))
    op.add_column('skills', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('skills', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.drop_column('skills', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('level', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.drop_column('skills', 'updated_at')
    op.drop_column('skills', 'created_at')
    op.drop_column('skills', 'proficiency')
    op.drop_column('skills', 'category')
    # ### end Alembic commands ###
