"""update projects table

Revision ID: 7b8843bfb0e4
Revises: 1309be066672
Create Date: 2025-07-20 13:53:39.778158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b8843bfb0e4'
down_revision: Union[str, Sequence[str], None] = '1309be066672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('technologies', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('live_url', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('code_url', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('projects', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('link', sa.VARCHAR(), nullable=True))
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'created_at')
    op.drop_column('projects', 'code_url')
    op.drop_column('projects', 'live_url')
    op.drop_column('projects', 'technologies')
    # ### end Alembic commands ###
