"""Update experience model to match project structure

Revision ID: bc037de7c51d
Revises: e0c0d19a6854
Create Date: 2025-07-20 16:24:16.150874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc037de7c51d'
down_revision: Union[str, Sequence[str], None] = 'e0c0d19a6854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('title', sa.String(), nullable=True))
    op.add_column('experiences', sa.Column('technologies', sa.JSON(), nullable=True))
    op.add_column('experiences', sa.Column('live_url', sa.String(), nullable=True))
    op.add_column('experiences', sa.Column('code_url', sa.String(), nullable=True))
    op.add_column('experiences', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('experiences', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('experiences', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.alter_column('experiences', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('experiences', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_experiences_company'), table_name='experiences')
    op.create_index(op.f('ix_experiences_title'), 'experiences', ['title'], unique=False)
    op.drop_column('experiences', 'company')
    op.drop_column('experiences', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('position', sa.VARCHAR(), nullable=True))
    op.add_column('experiences', sa.Column('company', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_experiences_title'), table_name='experiences')
    op.create_index(op.f('ix_experiences_company'), 'experiences', ['company'], unique=False)
    op.alter_column('experiences', 'end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('experiences', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('experiences', 'updated_at')
    op.drop_column('experiences', 'created_at')
    op.drop_column('experiences', 'image_url')
    op.drop_column('experiences', 'code_url')
    op.drop_column('experiences', 'live_url')
    op.drop_column('experiences', 'technologies')
    op.drop_column('experiences', 'title')
    # ### end Alembic commands ###
