"""rename school to institution in educations

Revision ID: c6f1a1f17e6c
Revises: f49590229cfd
Create Date: 2025-07-19 21:25:43.800882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f1a1f17e6c'
down_revision: Union[str, Sequence[str], None] = 'f49590229cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('educations', sa.Column('institution', sa.String(), nullable=True))
    op.drop_index(op.f('ix_educations_school'), table_name='educations')
    op.create_index(op.f('ix_educations_institution'), 'educations', ['institution'], unique=False)
    op.drop_column('educations', 'school')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('educations', sa.Column('school', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_educations_institution'), table_name='educations')
    op.create_index(op.f('ix_educations_school'), 'educations', ['school'], unique=False)
    op.drop_column('educations', 'institution')
    # ### end Alembic commands ###
